# Production infrastructure for __APP_NAME__.
#
# This is a thin wrapper around the shared `static-site` module. It owns ONLY
# this app's resources; the hosted zone, ACM certificate, and WAF are shared
# primitives the module looks up read-only.
#
# Generated by the deploy-to-prod skill. Re-running the skill is safe.

terraform {
  required_version = ">= 1.10.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0.0"
    }
  }

  # Per-app state object in the shared state bucket, with S3-native locking.
  backend "s3" {
    bucket       = "robmclaughl-in-terraform-state"
    key          = "apps/__APP_NAME__/terraform.tfstate"
    region       = "us-west-2"
    encrypt      = true
    use_lockfile = true
  }
}

provider "aws" {
  region = "us-west-2"

  default_tags {
    tags = {
      Project   = "robmclaughl.in"
      App       = "__APP_NAME__"
      ManagedBy = "terraform"
    }
  }
}

# CloudFront's ACM certificate and the CLOUDFRONT-scoped WAF live in us-east-1.
provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"

  default_tags {
    tags = {
      Project   = "robmclaughl.in"
      App       = "__APP_NAME__"
      ManagedBy = "terraform"
    }
  }
}

module "site" {
  source = "git::https://github.com/robmclaughliniv/robmclaughl.in.git//terraform/modules/static-site?ref=__MODULE_REF__"

  app_name  = "__APP_NAME__"
  subdomain = "__SUBDOMAIN__"
  repo      = "__REPO__"
  spa_mode  = __SPA_MODE__

  # API add-on. Set both to false for a purely static site.
  enable_api      = __ENABLE_API__
  enable_dynamodb = __ENABLE_DYNAMODB__

  providers = {
    aws           = aws
    aws.us_east_1 = aws.us_east_1
  }
}

# These outputs are the CI handoff contract — bootstrap.sh reads them and sets
# them as GitHub Actions repo variables.
output "role_arn" {
  description = "GitHub Actions OIDC deploy role ARN."
  value       = module.site.role_arn
}

output "bucket_name" {
  description = "S3 content bucket (deploy sync target)."
  value       = module.site.bucket_name
}

output "distribution_id" {
  description = "CloudFront distribution ID (invalidation target)."
  value       = module.site.distribution_id
}

output "site_url" {
  description = "Public site URL."
  value       = module.site.site_url
}

output "lambda_function_name" {
  description = "API Lambda name (null when the API add-on is disabled)."
  value       = module.site.lambda_function_name
}
